# Generated by Django 5.2.4 on 2025-07-23 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatcampusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=150, unique=True, verbose_name='topic name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, verbose_name='room name')),
                ('room_description', models.TextField(verbose_name='room description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_owner', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='room_participants', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_topic', to='chatcampusapp.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['topic_name'], name='chatcampusa_topic_n_f49dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['topic'], name='chatcampusa_topic_i_dd4b30_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_name'], name='chatcampusa_room_na_f7a580_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_description'], name='chatcampusa_room_de_a65730_idx'),
        ),
    ]
